### ISSUE TITLE
Question on AddConstants

### ISSUE THREAD

**Issue by robbelouwet** [ErikP0/forkskinny-c#1]
Hello Erik,

Could you shed some light on what you are doing here?

https://github.com/ErikP0/forkskinny-c/blob/ee30c666c301ee0ac1097dac1e40db17ebf51c6e/forkskinny64-cipher.c#L128
I don't really understand what's happening, this doesn't look like you're plainly adding the round constants to the round key. It looks like you're xor'ing values to the first and third cell of the first row, but these aren't the correct positions where the round constants should go according to the (Fork)SKINNY paper?
In the AddConstant step in the SKINNY paper, the round constants are C0, C1 and 0x2, to be added to the first, fifth and 9th cell resp. How does this relate to what your doing? Like, I understand there may be some increased performance by outsourcing the precomputed round constants to the round keys, but I don't see the relation between what you are doing here, and the AddConstant step in the SKINNY (or ForkSKINNY) paper. 

https://github.com/ErikP0/forkskinny-c/blob/ee30c666c301ee0ac1097dac1e40db17ebf51c6e/forkskinny64-cipher.c#L280
Also, why are you OR'ing `0x2000000000ULL` here?

**Comment by ErikP0** [comment]
In this line
https://github.com/ErikP0/forkskinny-c/blob/ee30c666c301ee0ac1097dac1e40db17ebf51c6e/forkskinny64-cipher.c#L128
`((RC[index] & 0x0F) << 4)` is c0, and here
https://github.com/ErikP0/forkskinny-c/blob/ee30c666c301ee0ac1097dac1e40db17ebf51c6e/forkskinny64-cipher.c#L129
`(RC[index] & 0x70)` is c1. 
The remaining 0x2 is added during the encryption/decryption since the round tweakey is only the top half of the state.
https://github.com/ErikP0/forkskinny-c/blob/ee30c666c301ee0ac1097dac1e40db17ebf51c6e/forkskinny64-cipher.c#L283

Now there is a mysterious `0x2000` xored in line 128. In the forkcipher paper [ePrint 2019/1004](https://eprint.iacr.org/2019/1004.pdf) in the appendix on page 40, you will find 

> As suggested in the SKINNY specification, when there is some tweak material, we add an extra 1 in the constant matrix from AddConstants, every round at line 0, column 2, to the second bit)

This  `0x2000` xored in line 128 sets the 1 in the third cell since Forkskinny-64-192 has a tweak of size 32 bits. This is extremely hidden in both the SKINNY and the Forkskinny paper.

The same observations can be made for the cases where the state is represented in larger registers.

I hope this helps :)
